import {Card} from '../../models/card';
import { CardSet } from '../../models/card-set';
import { CardsInRarity } from '../../models/cards-in-rarity';

var CARDS: Card[] = [
    new Card(1,'Shuckle','Uncommon',''),
    new Card(2,'Burmy','Common',''),
    new Card(3,'Wormadam','Uncommon',''),
    new Card(4,'Mothim','Rare',''),
    new Card(5,'Snivy','Common',''),
    new Card(6,'Servine','Uncommon',''),
    new Card(7,'Serperior','Rare',''),
    new Card(8,'Deerling','Common',''),
    new Card(9,'Moltres','Rare',''),
    new Card(10,'Fennekin','Common',''),
    new Card(11,'Fennekin','Common',''),
    new Card(12,'Braixen','Uncommon',''),
    new Card(13,'Delphox','Rare Holo',''),
    new Card(14,'Delphox','Rare BREAK',''),
    new Card(15,'Seel','Common',''),
    new Card(16,'Dewgong','Uncommon',''),
    new Card(17,'Omanyte','Uncommon',''),
    new Card(18,'Omastar','Rare',''),
    new Card(19,'Omastar','Rare BREAK',''),
    new Card(20,'Glaceon','Rare Holo ex',''),
    new Card(21,'White Kyurem','Rare Holo',''),
    new Card(22,'Binacle','Common',''),
    new Card(23,'Barbaracle','Rare',''),
    new Card(24,'Rotom','Rare',''),
    new Card(25,'Alakazam','Rare Holo ex',''),
    new Card(26,'Alakazam','Rare Holo ex',''),
    new Card(27,'Koffing','Common',''),
    new Card(28,'Weezing','Uncommon',''),
    new Card(29,'Mew','Rare Holo',''),
    new Card(30,'Spoink','Common',''),
    new Card(31,'Grumpig','Rare',''),
    new Card(32,'Gothita','Common',''),
    new Card(33,'Solosis','Common',''),
    new Card(34,'Duosion','Uncommon',''),
    new Card(35,'Reuniclus','Rare',''),
    new Card(36,'Diglett','Common',''),
    new Card(37,'Marowak','Rare',''),
    new Card(38,'Kabuto','Uncommon',''),
    new Card(39,'Kabutops','Rare',''),
    new Card(40,'Larvitar','Common',''),
    new Card(41,'Larvitar','Common',''),
    new Card(42,'Pupitar','Uncommon',''),
    new Card(43,'Regirock','Rare Holo ex',''),
    new Card(44,'Wormadam','Uncommon',''),
    new Card(45,'Riolu','Common',''),
    new Card(46,'Riolu','Common',''),
    new Card(47,'Lucario','Rare',''),
    new Card(48,'Hawlucha','Uncommon',''),
    new Card(49,'Carbink','Rare',''),
    new Card(50,'Carbink','Common',''),
    new Card(51,'Carbink','Rare BREAK',''),
    new Card(52,'Zygarde','Uncommon',''),
    new Card(53,'Zygarde','Rare',''),
    new Card(54,'Zygarde','Rare Holo ex',''),
    new Card(55,'Umbreon','Rare Holo ex',''),
    new Card(56,'Tyranitar','Rare Holo',''),
    new Card(57,'Vullaby','Common',''),
    new Card(58,'Mandibuzz','Rare',''),
    new Card(59,'Wormadam','Uncommon',''),
    new Card(60,'Bronzor','Common',''),
    new Card(61,'Bronzong','Rare',''),
    new Card(62,'Bronzong','Rare BREAK',''),
    new Card(63,'Lucario','Rare Holo',''),
    new Card(64,'Genesect','Rare Holo ex',''),
    new Card(65,'Jigglypuff','Common',''),
    new Card(66,'Wigglytuff','Uncommon',''),
    new Card(67,'Mr. Mime','Rare',''),
    new Card(68,'Snubbull','Common',''),
    new Card(69,'Altaria','Rare Holo ex',''),
    new Card(70,'Cottonee','Common',''),
    new Card(71,'Whimsicott','Uncommon',''),
    new Card(72,'Diancie','Rare Holo ex',''),
    new Card(73,'Kingdra','Rare Holo ex',''),
    new Card(74,'Meowth','Common',''),
    new Card(75,'Kangaskhan','Uncommon',''),
    new Card(76,'Aerodactyl','Rare',''),
    new Card(77,'Snorlax','Rare',''),
    new Card(78,'Lugia','Rare',''),
    new Card(79,'Lugia','Rare BREAK',''),
    new Card(80,'Whismur','Common',''),
    new Card(81,'Loudred','Uncommon',''),
    new Card(82,'Exploud','Rare',''),
    new Card(83,'Altaria','Rare Holo ex',''),
    new Card(84,'Audino','Rare Holo ex',''),
    new Card(85,'Audino','Rare Holo ex',''),
    new Card(86,'Minccino','Common',''),
    new Card(87,'Minccino','Common',''),
    new Card(88,'Cinccino','Uncommon',''),
    new Card(89,'Cinccino','Uncommon',''),
    new Card(90,'Alakazam Spirit Link','Uncommon',''),
    new Card(91,'Altaria Spirit Link','Uncommon',''),
    new Card(92,'Audino Spirit Link','Uncommon',''),
    new Card(93,'Bent Spoon','Uncommon',''),
    new Card(94,'Chaos Tower','Uncommon',''),
    new Card(95,'Devolution Spray','Uncommon',''),
    new Card(96,'Dome Fossil Kabuto','Uncommon',''),
    new Card(97,'Energy Pouch','Uncommon',''),
    new Card(98,'Energy Reset','Uncommon',''),
    new Card(99,'Fairy Drop','Uncommon',''),
    new Card(100,'Fairy Garden','Uncommon',''),
    new Card(101,'Fossil Excavation Kit','Uncommon',''),
    new Card(102,'Helix Fossil Omanyte','Uncommon',''),
    new Card(103,'Lass\'s Special','Uncommon',''),
    new Card(104,'Mega Catcher','Uncommon',''),
    new Card(105,'N','Uncommon',''),
    new Card(106,'Old Amber Aerodactyl','Uncommon',''),
    new Card(107,'Pokémon Fan Club','Uncommon',''),
    new Card(108,'Power Memory','Uncommon',''),
    new Card(109,'Random Receiver','Uncommon',''),
    new Card(110,'Scorched Earth','Uncommon',''),
    new Card(111,'Shauna','Uncommon',''),
    new Card(112,'Team Rocket\'s Handiwork','Uncommon',''),
    new Card(113,'Ultra Ball','Uncommon',''),
    new Card(114,'Double Colorless Energy','Uncommon',''),
    new Card(115,'Strong Energy','Uncommon',''),
    new Card(116,'Glaceon','Rare Ultra',''),
    new Card(117,'Alakazam','Rare Ultra',''),
    new Card(118,'Alakazam','Rare Ultra',''),
    new Card(119,'Umbreon','Rare Ultra',''),
    new Card(120,'Genesect','Rare Ultra',''),
    new Card(121,'Altaria','Rare Ultra',''),
    new Card(122,'Kingdra','Rare Ultra',''),
    new Card(123,'Altaria','Rare Ultra',''),
    new Card(124,'Team Rocket\'s Handiwork','Rare Ultra',''),
    new Card(125,'Alakazam','Rare Secret','')
];

var CARDS_IN_RARITY: CardsInRarity[] = [
    { rarity: 'Common', number: 3 },
    { rarity: 'Uncommon', number: 5 }
];

export var FATES_COLLIDE: CardSet = {
    id: 1,
    name: 'Fates Collide',
    cards: CARDS,
    cardsInRarity: CARDS_IN_RARITY
};
