import {Card} from '../../models/card';
import { CardSet } from '../../models/card-set';
import { CardsInRarity } from '../../models/cards-in-rarity';

var CARDS: Card[] = [
    new Card(1,'Venusaur-EX','Rare Holo ex','app/images/generations/Venusaur-EX.png'),
new Card(2,'MVenusaur-EX','Rare Holo ex','app/images/generations/MVenusaur-EX.png'),
new Card(3,'Caterpie','Common','app/images/generations/Caterpie.png'),
new Card(4,'Metapod','Uncommon','app/images/generations/Metapod.png'),
new Card(5,'Butterfree','Rare Holo','app/images/generations/Butterfree.png'),
new Card(6,'Paras','Common','app/images/generations/Paras.png'),
new Card(7,'Parasect','Rare','app/images/generations/Parasect.png'),
new Card(8,'Tangela','Common','app/images/generations/Tangela.png'),
new Card(9,'Pinsir','Rare','app/images/generations/Pinsir.png'),
new Card(10,'Leafeon-EX','Rare Holo ex','app/images/generations/Leafeon-EX.png'),
new Card(11,'Charizard-EX','Rare Holo ex','app/images/generations/Charizard-EX.png'),
new Card(12,'MCharizard-EX','Rare Holo ex','app/images/generations/MCharizard-EX.png'),
new Card(13,'Ninetales-EX','Rare Holo ex','app/images/generations/Ninetales-EX.png'),
new Card(14,'Ponyta','Common','app/images/generations/Ponyta.png'),
new Card(15,'Rapidash','Rare','app/images/generations/Rapidash.png'),
new Card(16,'Magmar','Common','app/images/generations/Magmar.png'),
new Card(17,'Blastoise-EX','Rare Holo ex','app/images/generations/Blastoise-EX.png'),
new Card(18,'MBlastoise-EX','Rare Holo ex','app/images/generations/MBlastoise-EX.png'),
new Card(19,'Shellder','Common','app/images/generations/Shellder.png'),
new Card(20,'Cloyster','Uncommon','app/images/generations/Cloyster.png'),
new Card(21,'Krabby','Common','app/images/generations/Krabby.png'),
new Card(22,'Magikarp','Common','app/images/generations/Magikarp.png'),
new Card(23,'Gyarados','Rare','app/images/generations/Gyarados.png'),
new Card(24,'Vaporeon-EX','Rare Holo ex','app/images/generations/Vaporeon-EX.png'),
new Card(25,'Articuno','Rare Holo','app/images/generations/Articuno.png'),
new Card(26,'Pikachu','Common','app/images/generations/Pikachu.png'),
new Card(27,'Raichu','Rare Holo','app/images/generations/Raichu.png'),
new Card(28,'Jolteon-EX','Rare Holo ex','app/images/generations/Jolteon-EX.png'),
new Card(29,'Zapdos','Rare Holo','app/images/generations/Zapdos.png'),
new Card(30,'Zubat','Common','app/images/generations/Zubat.png'),
new Card(31,'Golbat','Uncommon','app/images/generations/Golbat.png'),
new Card(32,'Slowpoke','Common','app/images/generations/Slowpoke.png'),
new Card(33,'Gastly','Common','app/images/generations/Gastly.png'),
new Card(34,'Haunter','Uncommon','app/images/generations/Haunter.png'),
new Card(35,'Gengar','Rare Holo','app/images/generations/Gengar.png'),
new Card(36,'Jynx','Rare','app/images/generations/Jynx.png'),
new Card(37,'Meowstic-EX','Rare Holo ex','app/images/generations/Meowstic-EX.png'),
new Card(38,'Diglett','Common','app/images/generations/Diglett.png'),
new Card(39,'Dugtrio','Rare','app/images/generations/Dugtrio.png'),
new Card(40,'Machop','Common','app/images/generations/Machop.png'),
new Card(41,'Machoke','Uncommon','app/images/generations/Machoke.png'),
new Card(42,'Machamp','Rare Holo','app/images/generations/Machamp.png'),
new Card(43,'Geodude','Common','app/images/generations/Geodude.png'),
new Card(44,'Graveler','Uncommon','app/images/generations/Graveler.png'),
new Card(45,'Golem','Rare Holo','app/images/generations/Golem.png'),
new Card(46,'Golem-EX','Rare Holo ex','app/images/generations/Golem-EX.png'),
new Card(47,'Hitmonlee','Rare','app/images/generations/Hitmonlee.png'),
new Card(48,'Hitmonchan','Rare','app/images/generations/Hitmonchan.png'),
new Card(49,'Rhyhorn','Common','app/images/generations/Rhyhorn.png'),
new Card(50,'Clefairy','Common','app/images/generations/Clefairy.png'),
new Card(51,'Clefable','Uncommon','app/images/generations/Clefable.png'),
new Card(52,'Mr. Mime','Uncommon','app/images/generations/Mr.Mime.png'),
new Card(53,'Meowth','Common','app/images/generations/Meowth.png'),
new Card(54,'Persian','Uncommon','app/images/generations/Persian.png'),
new Card(55,'Doduo','Common','app/images/generations/Doduo.png'),
new Card(56,'Dodrio','Rare','app/images/generations/Dodrio.png'),
new Card(57,'Tauros','Rare','app/images/generations/Tauros.png'),
new Card(58,'Snorlax','Rare','app/images/generations/Snorlax.png'),
new Card(59,'Clemont','Uncommon','app/images/generations/Clemont.png'),
new Card(60,'Crushing Hammer','Uncommon','app/images/generations/CrushingHammer.png'),
new Card(61,'Energy Switch','Uncommon','app/images/generations/EnergySwitch.png'),
new Card(62,'Evosoda','Uncommon','app/images/generations/Evosoda.png'),
new Card(63,'Imakuni?','Uncommon','app/images/generations/Imakuni?.png'),
new Card(64,'Maintenance','Uncommon','app/images/generations/Maintenance.png'),
new Card(65,'Max Revive','Uncommon','app/images/generations/MaxRevive.png'),
new Card(66,'Olympia','Uncommon','app/images/generations/Olympia.png'),
new Card(67,'Poké Ball','Uncommon','app/images/generations/PokéBall.png'),
new Card(68,'Pokémon Center Lady','Uncommon','app/images/generations/PokémonCenterLady.png'),
new Card(69,'Pokémon Fan Club','Uncommon','app/images/generations/PokémonFanClub.png'),
new Card(70,'Revitalizer','Uncommon','app/images/generations/Revitalizer.png'),
new Card(71,'Red Card','Uncommon','app/images/generations/RedCard.png'),
new Card(72,'Shauna','Uncommon','app/images/generations/Shauna.png'),
new Card(73,'Team Flare Grunt','Uncommon','app/images/generations/TeamFlareGrunt.png'),
new Card(74,'Double Colorless Energy','Uncommon','app/images/generations/DoubleColorlessEnergy.png'),
new Card(75,'Grass Energy','Common','app/images/generations/GrassEnergy.png'),
new Card(76,'Fire Energy','Common','app/images/generations/FireEnergy.png'),
new Card(77,'Water Energy','Common','app/images/generations/WaterEnergy.png'),
new Card(78,'Lightning Energy','Common','app/images/generations/LightningEnergy.png'),
new Card(79,'Psychic Energy','Common','app/images/generations/PsychicEnergy.png'),
new Card(80,'Fighting Energy','Common','app/images/generations/FightingEnergy.png'),
new Card(81,'Darkness Energy','Common','app/images/generations/DarknessEnergy.png'),
new Card(82,'Metal Energy','Common','app/images/generations/MetalEnergy.png'),
new Card(83,'Fairy Energy','Common','app/images/generations/FairyEnergy.png'),
];

var CARDS_IN_RARITY: CardsInRarity[] = [
    { rarity: 'Common', number: 1 },
    { rarity: 'Uncommon', number: 5 }
];

export var GENERATIONS: CardSet = {
    id: 1,
    name: 'Generations',
    cards: CARDS,
    cardsInRarity: CARDS_IN_RARITY
};
