import {Card} from '../../models/card';
import { CardSet } from '../../models/card-set';
import { CardsInRarity } from '../../models/cards-in-rarity';

var CARDS: Card[] = [
    new Card(1,'Shuckle','Uncommon','app/images/fatescollide/Shuckle.png'),
new Card(2,'Burmy','Common','app/images/fatescollide/Burmy.png'),
new Card(3,'Wormadam','Uncommon','app/images/fatescollide/Wormadam.png'),
new Card(4,'Mothim','Rare','app/images/fatescollide/Mothim.png'),
new Card(5,'Snivy','Common','app/images/fatescollide/Snivy.png'),
new Card(6,'Servine','Uncommon','app/images/fatescollide/Servine.png'),
new Card(7,'Serperior','Rare','app/images/fatescollide/Serperior.png'),
new Card(8,'Deerling','Common','app/images/fatescollide/Deerling.png'),
new Card(9,'Moltres','Rare','app/images/fatescollide/Moltres.png'),
new Card(10,'Fennekin','Common','app/images/fatescollide/Fennekin.png'),
new Card(11,'Fennekin','Common','app/images/fatescollide/Fennekin.png'),
new Card(12,'Braixen','Uncommon','app/images/fatescollide/Braixen.png'),
new Card(13,'Delphox','Rare Holo','app/images/fatescollide/Delphox.png'),
new Card(14,'DelphoxBREAK','Rare BREAK','app/images/fatescollide/DelphoxBREAK.png'),
new Card(15,'Seel','Common','app/images/fatescollide/Seel.png'),
new Card(16,'Dewgong','Uncommon','app/images/fatescollide/Dewgong.png'),
new Card(17,'Omanyte','Uncommon','app/images/fatescollide/Omanyte.png'),
new Card(18,'Omastar','Rare','app/images/fatescollide/Omastar.png'),
new Card(19,'OmastarBREAK','Rare BREAK','app/images/fatescollide/OmastarBREAK.png'),
new Card(20,'Glaceon-EX','Rare Holo ex','app/images/fatescollide/Glaceon-EX.png'),
new Card(21,'White Kyurem','Rare Holo','app/images/fatescollide/WhiteKyurem.png'),
new Card(22,'Binacle','Common','app/images/fatescollide/Binacle.png'),
new Card(23,'Barbaracle','Rare','app/images/fatescollide/Barbaracle.png'),
new Card(24,'Rotom','Rare','app/images/fatescollide/Rotom.png'),
new Card(25,'Alakazam-EX','Rare Holo ex','app/images/fatescollide/Alakazam-EX.png'),
new Card(26,'MAlakazam-EX','Rare Holo ex','app/images/fatescollide/MAlakazam-EX.png'),
new Card(27,'Koffing','Common','app/images/fatescollide/Koffing.png'),
new Card(28,'Weezing','Uncommon','app/images/fatescollide/Weezing.png'),
new Card(29,'Mew','Rare Holo','app/images/fatescollide/Mew.png'),
new Card(30,'Spoink','Common','app/images/fatescollide/Spoink.png'),
new Card(31,'Grumpig','Rare','app/images/fatescollide/Grumpig.png'),
new Card(32,'Gothita','Common','app/images/fatescollide/Gothita.png'),
new Card(33,'Solosis','Common','app/images/fatescollide/Solosis.png'),
new Card(34,'Duosion','Uncommon','app/images/fatescollide/Duosion.png'),
new Card(35,'Reuniclus','Rare','app/images/fatescollide/Reuniclus.png'),
new Card(36,'Diglett','Common','app/images/fatescollide/Diglett.png'),
new Card(37,'Marowak','Rare','app/images/fatescollide/Marowak.png'),
new Card(38,'Kabuto','Uncommon','app/images/fatescollide/Kabuto.png'),
new Card(39,'Kabutops','Rare','app/images/fatescollide/Kabutops.png'),
new Card(40,'Larvitar','Common','app/images/fatescollide/Larvitar.png'),
new Card(41,'Larvitar','Common','app/images/fatescollide/Larvitar.png'),
new Card(42,'Pupitar','Uncommon','app/images/fatescollide/Pupitar.png'),
new Card(43,'Regirock-EX','Rare Holo ex','app/images/fatescollide/Regirock-EX.png'),
new Card(44,'Wormadam','Uncommon','app/images/fatescollide/Wormadam.png'),
new Card(45,'Riolu','Common','app/images/fatescollide/Riolu.png'),
new Card(46,'Riolu','Common','app/images/fatescollide/Riolu.png'),
new Card(47,'Lucario','Rare','app/images/fatescollide/Lucario.png'),
new Card(48,'Hawlucha','Uncommon','app/images/fatescollide/Hawlucha.png'),
new Card(49,'Carbink','Rare','app/images/fatescollide/Carbink.png'),
new Card(50,'Carbink','Common','app/images/fatescollide/Carbink.png'),
new Card(51,'CarbinkBREAK','Rare BREAK','app/images/fatescollide/CarbinkBREAK.png'),
new Card(52,'Zygarde','Uncommon','app/images/fatescollide/Zygarde.png'),
new Card(53,'Zygarde','Rare','app/images/fatescollide/Zygarde.png'),
new Card(54,'Zygarde-EX','Rare Holo ex','app/images/fatescollide/Zygarde-EX.png'),
new Card(55,'Umbreon-EX','Rare Holo ex','app/images/fatescollide/Umbreon-EX.png'),
new Card(56,'Tyranitar','Rare Holo','app/images/fatescollide/Tyranitar.png'),
new Card(57,'Vullaby','Common','app/images/fatescollide/Vullaby.png'),
new Card(58,'Mandibuzz','Rare','app/images/fatescollide/Mandibuzz.png'),
new Card(59,'Wormadam','Uncommon','app/images/fatescollide/Wormadam.png'),
new Card(60,'Bronzor','Common','app/images/fatescollide/Bronzor.png'),
new Card(61,'Bronzong','Rare','app/images/fatescollide/Bronzong.png'),
new Card(62,'BronzongBREAK','Rare BREAK','app/images/fatescollide/BronzongBREAK.png'),
new Card(63,'Lucario','Rare Holo','app/images/fatescollide/Lucario.png'),
new Card(64,'Genesect-EX','Rare Holo ex','app/images/fatescollide/Genesect-EX.png'),
new Card(65,'Jigglypuff','Common','app/images/fatescollide/Jigglypuff.png'),
new Card(66,'Wigglytuff','Uncommon','app/images/fatescollide/Wigglytuff.png'),
new Card(67,'Mr. Mime','Rare','app/images/fatescollide/Mr.Mime.png'),
new Card(68,'Snubbull','Common','app/images/fatescollide/Snubbull.png'),
new Card(69,'MAltaria-EX','Rare Holo ex','app/images/fatescollide/MAltaria-EX.png'),
new Card(70,'Cottonee','Common','app/images/fatescollide/Cottonee.png'),
new Card(71,'Whimsicott','Uncommon','app/images/fatescollide/Whimsicott.png'),
new Card(72,'Diancie-EX','Rare Holo ex','app/images/fatescollide/Diancie-EX.png'),
new Card(73,'Kingdra-EX','Rare Holo ex','app/images/fatescollide/Kingdra-EX.png'),
new Card(74,'Meowth','Common','app/images/fatescollide/Meowth.png'),
new Card(75,'Kangaskhan','Uncommon','app/images/fatescollide/Kangaskhan.png'),
new Card(76,'Aerodactyl','Rare','app/images/fatescollide/Aerodactyl.png'),
new Card(77,'Snorlax','Rare','app/images/fatescollide/Snorlax.png'),
new Card(78,'Lugia','Rare','app/images/fatescollide/Lugia.png'),
new Card(79,'LugiaBREAK','Rare BREAK','app/images/fatescollide/LugiaBREAK.png'),
new Card(80,'Whismur','Common','app/images/fatescollide/Whismur.png'),
new Card(81,'Loudred','Uncommon','app/images/fatescollide/Loudred.png'),
new Card(82,'Exploud','Rare','app/images/fatescollide/Exploud.png'),
new Card(83,'Altaria-EX','Rare Holo ex','app/images/fatescollide/Altaria-EX.png'),
new Card(84,'Audino-EX','Rare Holo ex','app/images/fatescollide/Audino-EX.png'),
new Card(85,'MAudino-EX','Rare Holo ex','app/images/fatescollide/MAudino-EX.png'),
new Card(86,'Minccino','Common','app/images/fatescollide/Minccino.png'),
new Card(87,'Minccino','Common','app/images/fatescollide/Minccino.png'),
new Card(88,'Cinccino','Uncommon','app/images/fatescollide/Cinccino.png'),
new Card(89,'Cinccino','Uncommon','app/images/fatescollide/Cinccino.png'),
new Card(90,'Alakazam Spirit Link','Uncommon','app/images/fatescollide/AlakazamSpiritLink.png'),
new Card(91,'Altaria Spirit Link','Uncommon','app/images/fatescollide/AltariaSpiritLink.png'),
new Card(92,'Audino Spirit Link','Uncommon','app/images/fatescollide/AudinoSpiritLink.png'),
new Card(93,'Bent Spoon','Uncommon','app/images/fatescollide/BentSpoon.png'),
new Card(94,'Chaos Tower','Uncommon','app/images/fatescollide/ChaosTower.png'),
new Card(95,'Devolution Spray','Uncommon','app/images/fatescollide/DevolutionSpray.png'),
new Card(96,'Dome Fossil Kabuto','Uncommon','app/images/fatescollide/DomeFossilKabuto.png'),
new Card(97,'Energy Pouch','Uncommon','app/images/fatescollide/EnergyPouch.png'),
new Card(98,'Energy Reset','Uncommon','app/images/fatescollide/EnergyReset.png'),
new Card(99,'Fairy Drop','Uncommon','app/images/fatescollide/FairyDrop.png'),
new Card(100,'Fairy Garden','Uncommon','app/images/fatescollide/FairyGarden.png'),
new Card(101,'Fossil Excavation Kit','Uncommon','app/images/fatescollide/FossilExcavationKit.png'),
new Card(102,'Helix Fossil Omanyte','Uncommon','app/images/fatescollide/HelixFossilOmanyte.png'),
new Card(103,'Lass\'s Special','Uncommon','app/images/fatescollide/LasssSpecial.png'),
new Card(104,'Mega Catcher','Uncommon','app/images/fatescollide/MegaCatcher.png'),
new Card(105,'N','Uncommon','app/images/fatescollide/N.png'),
new Card(106,'Old Amber Aerodactyl','Uncommon','app/images/fatescollide/OldAmberAerodactyl.png'),
new Card(107,'Pokémon Fan Club','Uncommon','app/images/fatescollide/PokémonFanClub.png'),
new Card(108,'Power Memory','Uncommon','app/images/fatescollide/PowerMemory.png'),
new Card(109,'Random Receiver','Uncommon','app/images/fatescollide/RandomReceiver.png'),
new Card(110,'Scorched Earth','Uncommon','app/images/fatescollide/ScorchedEarth.png'),
new Card(111,'Shauna','Uncommon','app/images/fatescollide/Shauna.png'),
new Card(112,'Team Rocket\'s Handiwork','Uncommon','app/images/fatescollide/TeamRocketsHandiwork.png'),
new Card(113,'Ultra Ball','Uncommon','app/images/fatescollide/UltraBall.png'),
new Card(114,'Double Colorless Energy','Uncommon','app/images/fatescollide/DoubleColorlessEnergy.png'),
new Card(115,'Strong Energy','Uncommon','app/images/fatescollide/StrongEnergy.png'),
new Card(116,'Glaceon','Rare Ultra','app/images/fatescollide/Glaceon.png'),
new Card(117,'Alakazam','Rare Ultra','app/images/fatescollide/Alakazam.png'),
new Card(118,'MAlakazam','Rare Ultra','app/images/fatescollide/MAlakazam.png'),
new Card(119,'Umbreon','Rare Ultra','app/images/fatescollide/Umbreon.png'),
new Card(120,'Genesect','Rare Ultra','app/images/fatescollide/Genesect.png'),
new Card(121,'MAltaria','Rare Ultra','app/images/fatescollide/MAltaria.png'),
new Card(122,'Kingdra','Rare Ultra','app/images/fatescollide/Kingdra.png'),
new Card(123,'Altaria','Rare Ultra','app/images/fatescollide/Altaria.png'),
new Card(124,'Team Rocket\'s Handiwork','Rare Ultra','app/images/fatescollide/TeamRocketsHandiwork.png'),
new Card(125,'Alakazam','Rare Secret','app/images/fatescollide/Alakazam.png'),
];

var CARDS_IN_RARITY: CardsInRarity[] = [
    { rarity: 'Common', number: 3 },
    { rarity: 'Uncommon', number: 5 }
];

export var FATES_COLLIDE: CardSet = {
    id: 1,
    name: 'Fates Collide',
    cards: CARDS,
    cardsInRarity: CARDS_IN_RARITY
};
