import {Card} from '../../models/card';
import { CardSet } from '../../models/card-set';
import { CardsInRarity } from '../../models/cards-in-rarity';

var CARDS: Card[] = [
    new Card(1,'Venusaur','Rare Holo ex',''),
new Card(2,'Venusaur','Rare Holo ex',''),
new Card(3,'Caterpie','Common',''),
new Card(4,'Metapod','Uncommon',''),
new Card(5,'Butterfree','Rare Holo',''),
new Card(6,'Paras','Common',''),
new Card(7,'Parasect','Rare',''),
new Card(8,'Tangela','Common',''),
new Card(9,'Pinsir','Rare',''),
new Card(10,'Leafeon','Rare Holo ex',''),
new Card(11,'Charizard','Rare Holo ex',''),
new Card(12,'Charizard','Rare Holo ex',''),
new Card(13,'Ninetales','Rare Holo ex',''),
new Card(14,'Ponyta','Common',''),
new Card(15,'Rapidash','Rare',''),
new Card(16,'Magmar','Common',''),
new Card(17,'Blastoise','Rare Holo ex',''),
new Card(18,'Blastoise','Rare Holo ex',''),
new Card(19,'Shellder','Common',''),
new Card(20,'Cloyster','Uncommon',''),
new Card(21,'Krabby','Common',''),
new Card(22,'Magikarp','Common',''),
new Card(23,'Gyarados','Rare',''),
new Card(24,'Vaporeon','Rare Holo ex',''),
new Card(25,'Articuno','Rare Holo',''),
new Card(26,'Pikachu','Common',''),
new Card(27,'Raichu','Rare Holo',''),
new Card(28,'Jolteon','Rare Holo ex',''),
new Card(29,'Zapdos','Rare Holo',''),
new Card(30,'Zubat','Common',''),
new Card(31,'Golbat','Uncommon',''),
new Card(32,'Slowpoke','Common',''),
new Card(33,'Gastly','Common',''),
new Card(34,'Haunter','Uncommon',''),
new Card(35,'Gengar','Rare Holo',''),
new Card(36,'Jynx','Rare',''),
new Card(37,'Meowstic','Rare Holo ex',''),
new Card(38,'Diglett','Common',''),
new Card(39,'Dugtrio','Rare',''),
new Card(40,'Machop','Common',''),
new Card(41,'Machoke','Uncommon',''),
new Card(42,'Machamp','Rare Holo',''),
new Card(43,'Geodude','Common',''),
new Card(44,'Graveler','Uncommon',''),
new Card(45,'Golem','Rare Holo',''),
new Card(46,'Golem','Rare Holo ex',''),
new Card(47,'Hitmonlee','Rare',''),
new Card(48,'Hitmonchan','Rare',''),
new Card(49,'Rhyhorn','Common',''),
new Card(50,'Clefairy','Common',''),
new Card(51,'Clefable','Uncommon',''),
new Card(52,'Mr. Mime','Uncommon',''),
new Card(53,'Meowth','Common',''),
new Card(54,'Persian','Uncommon',''),
new Card(55,'Doduo','Common',''),
new Card(56,'Dodrio','Rare',''),
new Card(57,'Tauros','Rare',''),
new Card(58,'Snorlax','Rare',''),
new Card(59,'Clemont','Uncommon',''),
new Card(60,'Crushing Hammer','Uncommon',''),
new Card(61,'Energy Switch','Uncommon',''),
new Card(62,'Evosoda','Uncommon',''),
new Card(63,'Imakuni?','Uncommon',''),
new Card(64,'Maintenance','Uncommon',''),
new Card(65,'Max Revive','Uncommon',''),
new Card(66,'Olympia','Uncommon',''),
new Card(67,'Poké Ball','Uncommon',''),
new Card(68,'Pokémon Center Lady','Uncommon',''),
new Card(69,'Pokémon Fan Club','Uncommon',''),
new Card(70,'Revitalizer','Uncommon',''),
new Card(71,'Red Card','Uncommon',''),
new Card(72,'Shauna','Uncommon',''),
new Card(73,'Team Flare Grunt','Uncommon',''),
new Card(74,'Double Colorless Energy','Uncommon',''),
new Card(75,'Grass Energy','Common',''),
new Card(76,'Fire Energy','Common',''),
new Card(77,'Water Energy','Common',''),
new Card(78,'Lightning Energy','Common',''),
new Card(79,'Psychic Energy','Common',''),
new Card(80,'Fighting Energy','Common',''),
new Card(81,'Darkness Energy','Common',''),
new Card(82,'Metal Energy','Common',''),
new Card(83,'Fairy Energy','Common','')
];

var CARDS_IN_RARITY: CardsInRarity[] = [
    { rarity: 'B', number: 1 },
    { rarity: 'C', number: 5 }
];

export var GENERATIONS: CardSet = {
    id: 1,
    name: 'Generations',
    cards: CARDS,
    cardsInRarity: CARDS_IN_RARITY
};
