import {Card} from '../../models/card';
import { CardSet } from '../../models/card-set';
import { CardsInRarity } from '../../models/cards-in-rarity';

var CARDS: Card[] = [
    new Card(1,'Supreme Heavenly Emperor Dragon, Defeat Flare Dragon','GR+SGR','app/images/card-fight/set7/SupremeHeavenlyEmperorDragon,DefeatFlareDragon.png'),
    new Card(2,'Black Seraph, Gavrail','RRR+SP','app/images/card-fight/set7/BlackSeraph,Gavrail.png'),
    new Card(3,'Knight of Spring\'s Light, Perimore','RRR+SP','app/images/card-fight/set7/KnightofSpringsLight,Perimore.png'),
    new Card(4,'Supreme Heavenly Emperor Dragon, Dragonic Blademaster "Taiten"','RRR+SP','app/images/card-fight/set7/SupremeHeavenlyEmperorDragon,DragonicBlademaster"Taiten".png'),
    new Card(5,'Super Cosmic Hero, X-gallop','RRR+SP','app/images/card-fight/set7/SuperCosmicHero,X-gallop.png'),
    new Card(6,'Cosmic Hero, Grandrevolver','RRR+SP','app/images/card-fight/set7/CosmicHero,Grandrevolver.png'),
    new Card(7,'Wings of Reincarnation, Blade Wing Reijy','RRR+SP','app/images/card-fight/set7/WingsofReincarnation,BladeWingReijy.png'),
    new Card(8,'Interdimensional Dragon, Bind Time Dragon','RRR+SP','app/images/card-fight/set7/InterdimensionalDragon,BindTimeDragon.png'),
    new Card(9,'Chronofang Tiger','RRR+SP','app/images/card-fight/set7/ChronofangTiger.png'),
    new Card(10,'Holy Seraph, Suriel','RR','app/images/card-fight/set7/HolySeraph,Suriel.png'),
    new Card(11,'Doctroid Remnon','RR+SP','app/images/card-fight/set7/DoctroidRemnon.png'),
    new Card(12,'Black Spark, Munkar','RR','app/images/card-fight/set7/BlackSpark,Munkar.png'),
    new Card(13,'Golden Beast, Sleimy Flare','RR','app/images/card-fight/set7/GoldenBeast,SleimyFlare.png'),
    new Card(14,'Scarface Lion','RR','app/images/card-fight/set7/ScarfaceLion.png'),
    new Card(15,'Flame Wing Steel Beast, Denial Griffin','RR','app/images/card-fight/set7/FlameWingSteelBeast,DenialGriffin.png'),
    new Card(16,'Escort Dragon Attendant, Reas','RR+SP','app/images/card-fight/set7/EscortDragonAttendant,Reas.png'),
    new Card(17,'Super Cosmic Hero, X-carivou','RR','app/images/card-fight/set7/SuperCosmicHero,X-carivou.png'),
    new Card(18,'Cosmic Hero, Grandreef','RR+SP','app/images/card-fight/set7/CosmicHero,Grandreef.png'),
    new Card(19,'Nighttime Gentleman, Saint-Germain','RR','app/images/card-fight/set7/NighttimeGentleman,Saint-Germain.png'),
    new Card(20,'One-eyed Succubus','RR','app/images/card-fight/set7/One-eyedSuccubus.png'),
    new Card(21,'Highbrow Steam, Rapbanna','RR+SP','app/images/card-fight/set7/HighbrowSteam,Rapbanna.png'),
    new Card(22,'Retractor Sarakiel','R','app/images/card-fight/set7/RetractorSarakiel.png'),
    new Card(23,'Black Dream, Zabaniya','R','app/images/card-fight/set7/BlackDream,Zabaniya.png'),
    new Card(24,'Black Bomber, Malik','R','app/images/card-fight/set7/BlackBomber,Malik.png'),
    new Card(25,'Nurse of Smash Heart','R','app/images/card-fight/set7/NurseofSmashHeart.png'),
    new Card(26,'Dawngal','R','app/images/card-fight/set7/Dawngal.png'),
    new Card(27,'Wind Flame Lion, Wonder Ezel','R','app/images/card-fight/set7/WindFlameLion,WonderEzel.png'),
    new Card(28,'Sunshine Knight, Jeffrey','R','app/images/card-fight/set7/SunshineKnight,Jeffrey.png'),
    new Card(29,'Holy Mage, Irena','R','app/images/card-fight/set7/HolyMage,Irena.png'),
    new Card(30,'Spherical Lord Dragon','R','app/images/card-fight/set7/SphericalLordDragon.png'),
    new Card(31,'Dragon Fang Chain-bullet, Sutherland','R','app/images/card-fight/set7/DragonFangChain-bullet,Sutherland.png'),
    new Card(32,'Radiant Dragon','R','app/images/card-fight/set7/RadiantDragon.png'),
    new Card(33,'Dragon Knight, Roya','R','app/images/card-fight/set7/DragonKnight,Roya.png'),
    new Card(34,'Superlight Giant, Enigman Cross Ray','R','app/images/card-fight/set7/SuperlightGiant,EnigmanCrossRay.png'),
    new Card(35,'Great Cosmic Hero, Grandmantle','R','app/images/card-fight/set7/GreatCosmicHero,Grandmantle.png'),
    new Card(36,'Cosmic Hero, Grandrifter','R','app/images/card-fight/set7/CosmicHero,Grandrifter.png'),
    new Card(37,'Mask of Demonic Frenzy, Ericrius','R','app/images/card-fight/set7/MaskofDemonicFrenzy,Ericrius.png'),
    new Card(38,'Nine Break Hustler','R','app/images/card-fight/set7/NineBreakHustler.png'),
    new Card(39,'Doppel Vampir','R','app/images/card-fight/set7/DoppelVampir.png'),
    new Card(40,'Doreen the Thruster','R','app/images/card-fight/set7/DoreentheThruster.png'),
    new Card(41,'Blade Wing Tilith','R','app/images/card-fight/set7/BladeWingTilith.png'),
    new Card(42,'Interdimensional Beast, Floatgear Hippogriff','R','app/images/card-fight/set7/InterdimensionalBeast,FloatgearHippogriff.png'),
    new Card(43,'Steam Scalar, Emellanna','R','app/images/card-fight/set7/SteamScalar,Emellanna.png'),
    new Card(44,'Requiem Pegasus','C','app/images/card-fight/set7/RequiemPegasus.png'),
    new Card(45,'Treatment Nurse','C','app/images/card-fight/set7/TreatmentNurse.png'),
    new Card(46,'Frontal Celestial, Mariel','C','app/images/card-fight/set7/FrontalCelestial,Mariel.png'),
    new Card(47,'Laser Clutcher, Ke\'el','C','app/images/card-fight/set7/LaserClutcher,Keel.png'),
    new Card(48,'Drive Celestial, Armaiti','C','app/images/card-fight/set7/DriveCelestial,Armaiti.png'),
    new Card(49,'Celestial, Emergency Pegasus','C','app/images/card-fight/set7/Celestial,EmergencyPegasus.png'),
    new Card(50,'Drill Motor Nurse','C','app/images/card-fight/set7/DrillMotorNurse.png'),
    new Card(51,'Black Report, Ridwan','C','app/images/card-fight/set7/BlackReport,Ridwan.png'),
    new Card(52,'Surgery Angel','C','app/images/card-fight/set7/SurgeryAngel.png'),
    new Card(53,'Knight of Merciful Light, Bradott','C','app/images/card-fight/set7/KnightofMercifulLight,Bradott.png'),
    new Card(54,'Bullrgal','C','app/images/card-fight/set7/Bullrgal.png'),
    new Card(55,'Knight of Thin Sun, Marcia','C','app/images/card-fight/set7/KnightofThinSun,Marcia.png'),
    new Card(56,'Crimson Lion Beast, Howell','C','app/images/card-fight/set7/CrimsonLionBeast,Howell.png'),
    new Card(57,'Holy Mage, Connor','C','app/images/card-fight/set7/HolyMage,Connor.png'),
    new Card(58,'Iron Blue Lion, Scheidt','C','app/images/card-fight/set7/IronBlueLion,Scheidt.png'),
    new Card(59,'Bashgal','C','app/images/card-fight/set7/Bashgal.png'),
    new Card(60,'Player of the Holy Pipe, Herrie','C','app/images/card-fight/set7/PlayeroftheHolyPipe,Herrie.png'),
    new Card(61,'Dragon Knight, Basuit','C','app/images/card-fight/set7/DragonKnight,Basuit.png'),
    new Card(62,'Wyvern Strike, Garugy','C','app/images/card-fight/set7/WyvernStrike,Garugy.png'),
    new Card(63,'Dragon Knight, Nadim','C','app/images/card-fight/set7/DragonKnight,Nadim.png'),
    new Card(64,'Seal Dragon, Baraxya','C','app/images/card-fight/set7/SealDragon,Baraxya.png'),
    new Card(65,'Apex Dragon Mage, Kimnara','C','app/images/card-fight/set7/ApexDragonMage,Kimnara.png'),
    new Card(66,'Dragon Dancer, Marcel','C','app/images/card-fight/set7/DragonDancer,Marcel.png'),
    new Card(67,'Dragon Knight, Nadel','C','app/images/card-fight/set7/DragonKnight,Nadel.png'),
    new Card(68,'Seal Dragon, Doskin','C','app/images/card-fight/set7/SealDragon,Doskin.png'),
    new Card(69,'Serrated Dracokid','C','app/images/card-fight/set7/SerratedDracokid.png'),
    new Card(70,'Spiritburn Dragon','C','app/images/card-fight/set7/SpiritburnDragon.png'),
    new Card(71,'Inspire Yell Dragon','C','app/images/card-fight/set7/InspireYellDragon.png'),
    new Card(72,'Cosmic Hero, Grangurdy','C','app/images/card-fight/set7/CosmicHero,Grangurdy.png'),
    new Card(73,'Elegance Feather','C','app/images/card-fight/set7/EleganceFeather.png'),
    new Card(74,'Enigman Crescent','C','app/images/card-fight/set7/EnigmanCrescent.png'),
    new Card(75,'Intimidate Beast, Golmenas','C','app/images/card-fight/set7/IntimidateBeast,Golmenas.png'),
    new Card(76,'Enigman Squall','C','app/images/card-fight/set7/EnigmanSquall.png'),
    new Card(77,'Cosmic Hero, Grandvehicle','C','app/images/card-fight/set7/CosmicHero,Grandvehicle.png'),
    new Card(78,'Foxy Charmy','C','app/images/card-fight/set7/FoxyCharmy.png'),
    new Card(79,'Magical Inspector Tulpe','C','app/images/card-fight/set7/MagicalInspectorTulpe.png'),
    new Card(80,'Cosmic Hero, Grandhop','C','app/images/card-fight/set7/CosmicHero,Grandhop.png'),
    new Card(81,'Justice Gold','C','app/images/card-fight/set7/JusticeGold.png'),
    new Card(82,'Enigman Warm','C','app/images/card-fight/set7/EnigmanWarm.png'),
    new Card(83,'Operator Girl, Erika','C','app/images/card-fight/set7/OperatorGirl,Erika.png'),
    new Card(84,'Cosmic Hero, Grandskold','C','app/images/card-fight/set7/CosmicHero,Grandskold.png'),
    new Card(85,'Frosty Steeple','C','app/images/card-fight/set7/FrostySteeple.png'),
    new Card(86,'Tragic Claw','C','app/images/card-fight/set7/TragicClaw.png'),
    new Card(87,'Blade Wing Sycus','C','app/images/card-fight/set7/BladeWingSycus.png'),
    new Card(88,'Three-in the Dark','C','app/images/card-fight/set7/Three-intheDark.png'),
    new Card(89,'Combust Vampire','C','app/images/card-fight/set7/CombustVampire.png'),
    new Card(90,'Serpent Charmer','C','app/images/card-fight/set7/SerpentCharmer.png'),
    new Card(91,'Blade Wing Rhodopis','C','app/images/card-fight/set7/BladeWingRhodopis.png'),
    new Card(92,'Enigmatic Assassin','C','app/images/card-fight/set7/EnigmaticAssassin.png'),
    new Card(93,'Werbummbar Zoldat','C','app/images/card-fight/set7/WerbummbarZoldat.png'),
    new Card(94,'Square One Dragon','C','app/images/card-fight/set7/SquareOneDragon.png'),
    new Card(95,'Steam Knight, Mudal','C','app/images/card-fight/set7/SteamKnight,Mudal.png'),
    new Card(96,'Drain Valve Dragon','C','app/images/card-fight/set7/DrainValveDragon.png'),
    new Card(97,'Safety Observing Gear Diver','C','app/images/card-fight/set7/SafetyObservingGearDiver.png'),
    new Card(98,'Steam Fighter, Attabu','C','app/images/card-fight/set7/SteamFighter,Attabu.png'),
    new Card(99,'Parallel Barrel Dragon','C','app/images/card-fight/set7/ParallelBarrelDragon.png'),
    new Card(100,'Steam Fighter, Nanneya','C','app/images/card-fight/set7/SteamFighter,Nanneya.png'),
    new Card(101,'Tooth Edge Dracokid','C','app/images/card-fight/set7/ToothEdgeDracokid.png'),
    new Card(102,'Steam Schara, Lange','C','app/images/card-fight/set7/SteamSchara,Lange.png')
];

var CARDS_IN_RARITY: CardsInRarity[] = [
    { rarity: 'C', number: 4 },
    { rarity: 'R', number: 1 }
];

export var GLORIUS_BRAVERY: CardSet = {
    id: 1,
    name: 'Glorius Bravery',
    cards: CARDS,
    cardsInRarity: CARDS_IN_RARITY
};
