import {Card} from '../../models/card';
import { CardSet } from '../../models/card-set';
import { CardsInRarity } from '../../models/cards-in-rarity';

var CARDS: Card[] = [
    new Card(1,'Ranunculus in Glorious Bloom, Ahsha','GR','app/images/card-fight/set6/RanunculusinGloriousBloom--Ahsha.png'),
    new Card(2,'Counteroffensive Knight, Suleiman','RRR+SP','app/images/card-fight/set6/CounteroffensiveKnight--Suleiman.png'),
    new Card(3,'Dark Dragon, Spectral Blaster "Diablo"','RRR+SP','app/images/card-fight/set6/DarkDragon--SpectralBlasterDiablo.png'),
    new Card(4,'Whirlwind of Darkness, Vortimer "Diablo"','RRR+SP','app/images/card-fight/set6/WhirlwindofDarkness--VortimerDiablo.png'),
    new Card(5,'Meteokaiser, Victor','RRR+SP','app/images/card-fight/set6/Meteokaiser--Victor.png'),
    new Card(6,'Exxtreme Battler, Danshark','RRR+SP','app/images/card-fight/set6/ExxtremeBattler--Danshark.png'),
    new Card(7,'Mist Phantasm Pirate King, Nightrose','RRR+SP','app/images/card-fight/set6/MistPhantasmPirateKing--Nightrose.png'),
    new Card(8,'Ghoul Dragon, Gast Dragon','RRR+SP','app/images/card-fight/set6/GhoulDragon--GastDragon.png'),
    new Card(9,'Cornflower Flower Maiden, Ines','RRR+SP','app/images/card-fight/set6/CornflowerFlowerMaiden--Ines.png'),
    new Card(10,'Model Knight, Orhan','RR','app/images/card-fight/set6/ModelKnight--Orhan.png'),
    new Card(11,'Hope Keeper','RR+SP','app/images/card-fight/set6/HopeKeeper.png'),
    new Card(12,'Black Chain Flame Dance Formation, Hoel','RR','app/images/card-fight/set6/BlackChainFlameDanceFormation--Hoel.png'),
    new Card(13,'Extreme Battler, Headstrong-battle','RR','app/images/card-fight/set6/ExtremeBattler--Headstrong-battle.png'),
    new Card(14,'Extreme Battler, Break-pass','RR','app/images/card-fight/set6/ExtremeBattler--Break-pass.png'),
    new Card(15,'Curtain Call Announcer, Mephisto','RR','app/images/card-fight/set6/CurtainCallAnnouncer--Mephisto.png'),
    new Card(16,'Crescent Moon Juggler','RR','app/images/card-fight/set6/CrescentMoonJuggler.png'),
    new Card(17,'Hoop Master','RR+SP','app/images/card-fight/set6/HoopMaster.png'),
    new Card(18,'Witch Doctor of Languor, Negrolazy','RR','app/images/card-fight/set6/WitchDoctorofLanguor--Negrolazy.png'),
    new Card(19,'Waterspout Djinn','RR+SP','app/images/card-fight/set6/WaterspoutDjinn.png'),
    new Card(20,'Ideal Maiden, Thuria','RR','app/images/card-fight/set6/IdealMaiden--Thuria.png'),
    new Card(21,'Cherry Blossom Blizzard Maiden, Lilga','RR+SP','app/images/card-fight/set6/CherryBlossomBlizzardMaiden--Lilga.png'),
    new Card(22,'Knight of Light Order','R','app/images/card-fight/set6/KnightofLightOrder.png'),
    new Card(23,'Favored Pupil of Light and Dark, Llew','R','app/images/card-fight/set6/FavoredPupilofLightandDark--Llew.png'),
    new Card(24,'Headwind Knight, Selim','R','app/images/card-fight/set6/HeadwindKnight--Selim.png'),
    new Card(25,'Resurgent Knight, Stius','R','app/images/card-fight/set6/ResurgentKnight--Stius.png'),
    new Card(26,'Black Chain Spirit Dance Formation, Kahedin','R','app/images/card-fight/set6/BlackChainSpiritDanceFormation--Kahedin.png'),
    new Card(27,'Bassinet Knight, Oscar','R','app/images/card-fight/set6/BassinetKnight--Oscar.png'),
    new Card(28,'Ultimate Raizer Glory-hand','R','app/images/card-fight/set6/UltimateRaizerGlory-hand.png'),
    new Card(29,'Ultimate Raizer Speed-star','R','app/images/card-fight/set6/UltimateRaizerSpeed-star.png'),
    new Card(30,'Extreme Battler, Arbarail','R','app/images/card-fight/set6/ExtremeBattler--Arbarail.png'),
    new Card(31,'Extreme Battler, Malyaki','R','app/images/card-fight/set6/ExtremeBattler--Malyaki.png'),
    new Card(32,'Extreme Battler, Kabutron','R','app/images/card-fight/set6/ExtremeBattler--Kabutron.png'),
    new Card(33,'Flying Manticore','R','app/images/card-fight/set6/FlyingManticore.png'),
    new Card(34,'Cutie Paratrooper','R','app/images/card-fight/set6/CutieParatrooper.png'),
    new Card(35,'Cat Knight in High Boots','R','app/images/card-fight/set6/CatKnightinHighBoots.png'),
    new Card(36,'Ghostie Great King, Obadiah','R','app/images/card-fight/set6/GhostieGreatKing--Obadiah.png'),
    new Card(37,'Ruin Shade','R','app/images/card-fight/set6/RuinShade.png'),
    new Card(38,'Tommy the Ghostie Brothers','R','app/images/card-fight/set6/TommytheGhostieBrothers.png'),
    new Card(39,'Witch Doctor of the Powdered Bone, Negrobone','R','app/images/card-fight/set6/WitchDoctorofthePowderedBone--Negrobone.png'),
    new Card(40,'Forbidden Space Banshee','R','app/images/card-fight/set6/ForbiddenSpaceBanshee.png'),
    new Card(41,'Red-leaf Dragon','R','app/images/card-fight/set6/Red-leafDragon.png'),
    new Card(42,'Pure Maiden, Katrina','R','app/images/card-fight/set6/PureMaiden--Katrina.png'),
    new Card(43,'Peach Orchard Maiden, Elmy','R','app/images/card-fight/set6/PeachOrchardMaiden--Elmy.png'),
    new Card(44,'Shyngal','C','app/images/card-fight/set6/Shyngal.png'),
    new Card(45,'Hopesong Angel','C','app/images/card-fight/set6/HopesongAngel.png'),
    new Card(46,'Scouting Owl','C','app/images/card-fight/set6/ScoutingOwl.png'),
    new Card(47,'Blaster-friend, Barcgal','C','app/images/card-fight/set6/Blaster-friend--Barcgal.png'),
    new Card(48,'Knight of Powercharge','C','app/images/card-fight/set6/KnightofPowercharge.png'),
    new Card(49,'Sarugal','C','app/images/card-fight/set6/Sarugal.png'),
    new Card(50,'Floral Paladin, Flogal','C','app/images/card-fight/set6/FloralPaladin--Flogal.png'),
    new Card(51,'Deathspray Dragon','C','app/images/card-fight/set6/DeathsprayDragon.png'),
    new Card(52,'Blaster Axe','C','app/images/card-fight/set6/BlasterAxe.png'),
    new Card(53,'Greymyu','C','app/images/card-fight/set6/Greymyu.png'),
    new Card(54,'Dark Saga Painter','C','app/images/card-fight/set6/DarkSagaPainter.png'),
    new Card(55,'Blaster Rapier','C','app/images/card-fight/set6/BlasterRapier.png'),
    new Card(56,'Revenger, Darkbless Angel','C','app/images/card-fight/set6/Revenger--DarkblessAngel.png'),
    new Card(57,'Abyss Summoner','C','app/images/card-fight/set6/AbyssSummoner.png'),
    new Card(58,'Revenger of Vigor, Maur','C','app/images/card-fight/set6/RevengerofVigor--Maur.png'),
    new Card(59,'Blaster Dagger','C','app/images/card-fight/set6/BlasterDagger.png'),
    new Card(60,'Fullbau "Diablo"','C','app/images/card-fight/set6/FullbauDiablo.png'),
    new Card(61,'Grave Horn Unicorn','C','app/images/card-fight/set6/GraveHornUnicorn.png'),
    new Card(62,'Tactician of Godly-calculations, Orphe','C','app/images/card-fight/set6/TacticianofGodly-calculations--Orphe.png'),
    new Card(63,'Illegal Alchemist','C','app/images/card-fight/set6/IllegalAlchemist.png'),
    new Card(64,'Mage of the Rogue Eye, Arsur','C','app/images/card-fight/set6/MageoftheRogueEye--Arsur.png'),
    new Card(65,'Envoy of Righteousness, Crystaldevil','C','app/images/card-fight/set6/EnvoyofRighteousness--Crystaldevil.png'),
    new Card(66,'Beast Deity, Jackalord','C','app/images/card-fight/set6/BeastDeity--Jackalord.png'),
    new Card(67,'Babyface, Narcissus','C','app/images/card-fight/set6/Babyface--Narcissus.png'),
    new Card(68,'Master Kungfu','C','app/images/card-fight/set6/MasterKungfu.png'),
    new Card(69,'Kumar the Destroyer','C','app/images/card-fight/set6/KumartheDestroyer.png'),
    new Card(70,'Shinobiraizer','C','app/images/card-fight/set6/Shinobiraizer.png'),
    new Card(71,'Beast Deity, Horned Hulk','C','app/images/card-fight/set6/BeastDeity--HornedHulk.png'),
    new Card(72,'Rajadamnern Kid','C','app/images/card-fight/set6/RajadamnernKid.png'),
    new Card(73,'Turboraizer Custom','C','app/images/card-fight/set6/TurboraizerCustom.png'),
    new Card(74,'Totem Brothers','C','app/images/card-fight/set6/TotemBrothers.png'),
    new Card(75,'Training Therapist','C','app/images/card-fight/set6/TrainingTherapist.png'),
    new Card(76,'Beast Deity, Great Eater','C','app/images/card-fight/set6/BeastDeity--GreatEater.png'),
    new Card(77,'Perfect Referee, 2.99','C','app/images/card-fight/set6/PerfectReferee--2.99.png'),
    new Card(78,'Artilleryman','C','app/images/card-fight/set6/Artilleryman.png'),
    new Card(79,'Dreaming Pegasus','C','app/images/card-fight/set6/DreamingPegasus.png'),
    new Card(80,'Signal Snake Tamer','C','app/images/card-fight/set6/SignalSnakeTamer.png'),
    new Card(81,'Silver Thorn Assistant, Dixie','C','app/images/card-fight/set6/SilverThornAssistant--Dixie.png'),
    new Card(82,'Mighty Rogue, Nightstorm','C','app/images/card-fight/set6/MightyRogue--Nightstorm.png'),
    new Card(83,'Seven Seas Dragon Undead, Prisoner Dragon','C','app/images/card-fight/set6/SevenSeasDragonUndead--PrisonerDragon.png'),
    new Card(84,'Sleepless Skipper, Blackgick','C','app/images/card-fight/set6/SleeplessSkipper--Blackgick.png'),
    new Card(85,'Seven Seas Master Swordsman, Slash Shade','C','app/images/card-fight/set6/SevenSeasMasterSwordsman--SlashShade.png'),
    new Card(86,'Skeleton Cannoneer','C','app/images/card-fight/set6/SkeletonCannoneer.png'),
    new Card(87,'Witch Doctor of the Seven Seas, Raisruler','C','app/images/card-fight/set6/WitchDoctoroftheSevenSeas--Raisruler.png'),
    new Card(88,'Seven Seas Helmsman, Nightcrow','C','app/images/card-fight/set6/SevenSeasHelmsman--Nightcrow.png'),
    new Card(89,'Headstart Zombie','C','app/images/card-fight/set6/HeadstartZombie.png'),
    new Card(90,'Seven Seas Apprentice, Nightrunner','C','app/images/card-fight/set6/SevenSeasApprentice--Nightrunner.png'),
    new Card(91,'Assault Command, Carignan','C','app/images/card-fight/set6/AssaultCommand--Carignan.png'),
    new Card(92,'Looting Cutlass','C','app/images/card-fight/set6/LootingCutlass.png'),
    new Card(93,'Mick the Ghostie and Family','C','app/images/card-fight/set6/MicktheGhostieandFamily.png'),
    new Card(94,'Greenshot Elf','C','app/images/card-fight/set6/GreenshotElf.png'),
    new Card(95,'Maiden of Damask Rose','C','app/images/card-fight/set6/MaidenofDamaskRose.png'),
    new Card(96,'Cropmaker Dragon','C','app/images/card-fight/set6/CropmakerDragon.png'),
    new Card(97,'Af Roccoli','C','app/images/card-fight/set6/AfRoccoli.png'),
    new Card(98,'Tomboy Elf','C','app/images/card-fight/set6/TomboyElf.png'),
    new Card(99,'Maiden of Rambler','C','app/images/card-fight/set6/MaidenofRambler.png'),
    new Card(100,'Maiden of Noisette','C','app/images/card-fight/set6/MaidenofNoisette.png'),
    new Card(101,'Tsukken Don','C','app/images/card-fight/set6/TsukkenDon.png'),
    new Card(102,'Cosmos Pixy, Lizbeth','C','app/images/card-fight/set6/CosmosPixy--Lizbeth.png'),
    new Card(103,'Air Elemental, Twitterun','C','app/images/card-fight/set6/AirElemental--Twitterun.png'),
    new Card(104,'Blue Sky Knight, Altmile','SCR','app/images/card-fight/set6/BlueSkyKnight--Altmile.png'),
    new Card(105,'Ranunculus Flower Maiden, Ahsha','SCR','app/images/card-fight/set6/RanunculusFlowerMaiden--Ahsha.png'),
    new Card(106,'Exxtreme Battler, Victor','SCR','app/images/card-fight/set6/ExxtremeBattler--Victor.png'),
    new Card(107,'Revenger, Phantom Blaster "Abyss"','SCR','app/images/card-fight/set6/Revenger--PhantomBlasterAbyss.png')
];

var CARDS_IN_RARITY: CardsInRarity[] = [
    { rarity: 'C', number: 4 },
    { rarity: 'R', number: 1 }
];

var processBooster = function(cardsInBooster: Card[]) {
    cardsInBooster.push(CARDS[50]);
    cardsInBooster.push(CARDS[50]);
    cardsInBooster.push(CARDS[50]);
    return cardsInBooster;
};

export var TRANSCENSION_OF_BLADE: CardSet = {
    id: 1,
    name: 'Transcension of Blade',
    cards: CARDS,
    cardsInRarity: CARDS_IN_RARITY,
    processBooster: processBooster
};
